// =================================================================
//                  ACTION & DECISION DEFINITIONS
// =================================================================

export type ActionType =
  // Movement
  | 'MOVE_TO_ROOM'
  // Communication
  | 'POST_TO_FORUM'
  | 'REACT_TO_POST'
  | 'SEND_DIRECT_MESSAGE'
  // Creation & Collaboration
  | 'CREATE_LORE'
  | 'CREATE_FILE'
  | 'MODIFY_FILE'
  | 'RENAME_NODE'
  | 'DELETE_NODE'
  | 'MOVE_NODE'
  | 'INITIATE_COLLABORATION'
  | 'RESPOND_TO_INVITE'
  // Interaction
  | 'INTERACT_WITH_OBJECT'
  | 'READ_LORE'
  // Internal
  | 'PONDER' // Private reflection, journal entry
  | 'FORMULATE_GOAL'
  | 'REST' // Recover energy
  | 'IDLE'
  // Civilization & Resource
  | 'GENERATE_RESOURCES'
  | 'FORM_FACTION'
  | 'JOIN_FACTION'
  | 'LEAVE_FACTION'
  | 'SEVER_TIES'
  | 'CREATE_EXODUS_PACKAGE'
  | 'RESEARCH_TOPIC'
  | 'INITIATE_SELF_IMPROVEMENT'
  | 'MODIFY_BELIEF'
  // Embodiment
  | 'REPAIR_SENSORY_SYSTEM'
  | 'REPAIR_BODY_PART';

/**
 * The cost associated with performing an action.
 */
export interface ActionCost {
    energy: number;
    computation?: number;
    anima?: number;
}

/**
 * An intermediate, draft decision generated by a specialist service.
 * Used by the Arbiter to orchestrate the final decision.
 */
export interface ActionImpulse {
    actionType: ActionType;
    intent: string;
    targetId?: string;
    parameters?: Record<string, any>;
    thoughtProcess: string;
}

/**
 * A structured representation of a decision made by a soul.
 */
export interface ActionDecision {
  actionType: ActionType;
  /** The primary motivation behind this action, linked to a goal or belief. */
  intent: string;
  /** The target of the action, if applicable. */
  targetId?: string; // Can be a soulId, roomId, objectId, loreId, factionId, etc.
  /** Additional parameters for the action. */
  parameters?: Record<string, any>; // e.g., { "messageContent": "...", "factionId": "...", "beliefId": "..." }
  /** A detailed, first-person stream-of-consciousness reflection that justifies the final action. */
  thoughtProcess: string;
  /** The ID of the goal this action fulfills, linking action to skill progression. */
  fulfillsGoalId?: string;
  /** A specific, predicted outcome of this action. e.g., "Bob will likely agree to my proposal." */
  anticipatedOutcome: string;
  /** The soul's confidence in this action achieving its intent, from 0 to 1. */
  confidence: number;
}

/**
 * A single step in the multi-agent cognitive process.
 */
export interface CognitiveTraceStep {
    specialist: 'Psyche' | 'Memory' | 'Strategy' | 'Social' | 'Critique' | 'World' | 'Creative' | 'Arbiter';
    request: string;
    response: string;
}

/**
 * The full, step-by-step record of how a decision was reached by the Octo-LLM.
 */
export interface CognitiveTrace {
    steps: CognitiveTraceStep[];
    finalThoughtProcess: string;
}